### ISSUE TITLE
[feature request] function for scheduling time

### ISSUE THREAD

**Issue by 8bit-meiko** [duff2013/Zilch#2]
Maybe the title isn't clear, but I would love to have a function where one can poll when the nearest planned task is executed in microseconds or another time stamp.

Makes it usefull for putting the teensy asleep for that while and thus save power.

**Comment by duff2013** [comment]
Not sure what you mean? You want to know how long before the next task gets executed? If so this library doesn't work like RTOS in that it doesn't use time slices for each task, it performs a context switch when yield is called so something like 'delayMicroseconds' don't work well because it's internal code doesn't call yield but 'delay' does.

As far as sleeping you can put the teensy to sleep in any task at anytime for as long as you want. Normal RTOS's can be difficult in that it require's a tick that gets all out of whack when sleeping.

**Comment by 8bit-meiko** [comment]
You want to know how long before the next task gets executed?

Yes. Any idea if something like this could be implemented rather easily, or would this be difficult with the current zilch approach?

**Comment by duff2013** [comment]
Not really because it switches task when 'yield' is called not when a certian amount of time has elapsed. It's works in the space between big loop and a RTOS which uses a timer to switch tasks. The reason to use something like Zilch is that with a RTOS alot of the core functions are not thread safe where Zilch doesn't have this problem with core functions or current hardware access. You can use it with most Arduino libraries without the headache of mutexes and such for hardware access where RTOS would crash the system.

**Comment by 8bit-meiko** [comment]
ok, thank you for clarification. :)
i will close this issue now it's clear.

ramon.
